# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e0a35098e6dd9014a4d6f3ac5026f50578f5fc1caa05979c4a0dfba8aab69b7cbc12bbfd73a3f1cdda1a5ee0fa3fa4982c26e6b77bf7b9098b5c04912feff86

test:
  secret_key_base: c9c099d4e462109dbcf39dad8b7307419e8da823381368dfafde84a9672953560aba86e15c36ed59ff02fd0861c30412941cd138318823f907c4118ed1986b15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
